### ISSUE TITLE
Input style for select?

### ISSUE THREAD

**Issue by Schmiddinger** [creativetimofficial/paper-kit#13]
Is it possible to get a style for a select field, like the dropdown menu?

**Comment by alexandru-paduraru** [comment]
@Schmiddinger there are some styled select field in our PRO version: http://demos.creative-tim.com/paper-kit-2-pro/index.html, if you scroll to Footers. You can get that or you can use this: https://silviomoreto.github.io/bootstrap-select/

Hope this helps.

Best,
Alex
